Criação do dominio de cobranças
TrioParadaDuraa/mini-asaas pull request #21
Opened 2024-05-24 12:38 UTC by Danichs

### Impacto (Descrever o que foi feito)
- Criação do controller, service, domain e adapter do domínio de payment(cobranças);
- Crição da página de cadastro e visualização de cobranças;
- Criação de classes Utils para formatação de data e número(BigDecimal);
- Criação de Enum de status de pagamento e tipos de pagamento;

### PR Predecessora (Caso exista dependência de uma PR ou branch existente)

### Link da tarefa no GitHub Projects
[Dominio Payment](https://github.com/orgs/TrioParadaDuraa/projects/1/views/1?pane=issue&itemId=62413269)
### Link dos mockups (Se houver)

### Prints do desenvolvimento

2024-05-24 14:10 UTC, pedrosdev commented on grails-app/services/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.paymentType = params.paymentType
Aqui tu não teria que usar PaymentType.convert()?

2024-05-24 14:10 UTC, pedrosdev commented on grails-app/views/payment/show.gsp
> +      </div>
Acho que não precisa desse campo

2024-05-24 14:10 UTC, pedrosdev commented on src/main/groovy/com/mini/asaas/utils/FormatUtils.groovy
> +        return  outputSdf.format(date)
```suggestion
        return outputSdf.format(date)
```

2024-05-24 16:30 UTC, NayaneBatista approved these changes

2024-05-27 17:34 UTC, Thuran commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +            Payment payment = Payment.read(params.long('id'))
validar customer logado

2024-05-27 17:35 UTC, Thuran commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +                throw new Exception("Cobrança não encontrada")
Acho legal criarmos uma exception que queremos estourar a mensagem para o cliente. Algo como um `CustomerException` ou `CustomException`...
Ai podemos ter um catch para esse tipo e exibir sua própria mensagem para o client

2024-05-27 17:35 UTC, Thuran commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +            Long payerId = 1
esse dado não poderia vir junto no adapter?

2024-05-27 17:36 UTC, Thuran commented on grails-app/i18n/messages.properties
> +PaymentStatus.AWAITING_PAYMENT.label=Aguardando pagamento
é bom dar um espaço entre os tipos para facilitar leitura

2024-05-27 17:36 UTC, Thuran commented on src/main/groovy/com/mini/asaas/utils/enums/PaymentStatus.groovy
> +    RECEIVED,
Podemos ter o recebido em dinheiro também né?

2024-05-27 17:37 UTC, Thuran commented on grails-app/views/payment/index.gsp
> +            <select name="paymentType" id="paymentType">
será que não da de utlizar o `g:select` ?

2024-05-27 17:37 UTC, Thuran requested changes
Adicionar o @GrailsCompileStatic

2024-05-28 16:22 UTC, Thuran commented on src/main/groovy/com/mini/asaas/utils/enums/PaymentStatus.groovy
> +    MONEY
Acho que `RECEIVED_IN_CASH` fica mais claro, `MONEY` sozinho não diz nada para um status, até parece ser um `billingType`

2024-05-28 16:23 UTC, Thuran commented on src/main/groovy/com/mini/asaas/utils/enums/PaymentType.groovy
> +enum PaymentType {
Acho que `billingType` fica mais claro

2024-05-28 16:23 UTC, Thuran commented on grails-app/domain/com/mini/asaas/payment/Payment.groovy
> +    PaymentType paymentType
`billingType`

2024-05-28 16:33 UTC, Thuran approved these changes

2024-05-28 16:33 UTC, merged