Base Person
TrioParadaDuraa/mini-asaas pull request #3
Opened 2024-05-10 14:41 UTC by Danichs

- Criação da class de BasePerson que serve como base para criação do customer e payer.

2024-05-13 13:43 UTC, welingtonloh requested changes

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/enum/PersonType.groovy
> +package com.mini.asaas
```suggestion
package com.mini.asaas.customer
```
O que acham de já irmos organizando as classes em pacotes? agrupando por contexto

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/enum/PersonType.groovy
> +    NATURAL,
Pode deixar uma linha em branco, no inicio das classes e Enums, antes do primeiro item da enum

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/enum/PersonType.groovy
> +            } catch(Exception e) {
```suggestion
    public static PersonType convert(personType){
            try {
                return personType as PersonType
            } catch(Exception exception) {
```

Pensa que vcs podem receber uma String ou a propria Enum

Creio que pensando nesses dois casos de uso possiveis devemos simplificar dai

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/enum/PersonType.groovy
> +        return Holders.applicationContext.getBean("messageSource").getMessage("PersonType.${this}.label", null, "", new Locale("pt", "BR"))
Sugiro que a gente já encapsule isso em um Utils:
public static String getMessageProperty(String messageCode, List arguments) {
        return Holders.applicationContext.getBean("messageSource").getMessage(messageCode, arguments as Object[], new Locale("pt","BR"))
    }

Dessa forma não vai precisar repetir esse tratamento new Locale("pt", "BR") a cada lugar que precisarem recuperar uma mensagem

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/utils/BaseDomain.groovy
> +package com.mini.asaas.utils
com.mini.asaas.domain.base

Isso de criar o pacote domain é algo que vou sugerir nas classes tbm

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/utils/BaseDomain.groovy
> +    Date lastUpdated
Uma linha em branco entre os atributos, por code style

2024-05-13 13:43 UTC, welingtonloh commented on src/main/groovy/utils/BasePerson.groovy
> +
Pessoa não tem telefone?
Em qual campo vamos registrar o bairro?
Em qual campo vamos registrar o número da casa?
E se for uma casa nos fundos? não tem campo para o complemento do endereço?

Senti falta das contraints dos campos tbm

2024-05-13 18:27 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BaseDomain.groovy
> +
Remove essa linha em branco perdida

Insere uma linha em branco entre os atributos

Insere uma linha em branco entre o deleted e o mapping

Revisa todos as demais classes tbm em relação aos pontos que comentei

2024-05-13 18:29 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/utils/Utils.groovy
> +
A linha em branco que comentei antes é sempre no inicio da classe

Para os metodos não precisa

No final da classe tbm não precisa

2024-05-13 18:30 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +    String phoneNumber
```suggestion
    String phone
```

2024-05-13 18:31 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +    String complement
addressComplement

2024-05-13 18:32 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +        phoneNumber blank: false
Dá para usar size no phone

2024-05-13 18:33 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +        addressNumber blank: true, nullable: true
true? não seria preenchido com SN dai? de sem número

2024-05-14 12:19 UTC, pedrosdev commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +    String state
Faltou coloca as linhas em branco entre os atributos. O Loh disse que tem que ser nesse estilo:
```suggestion
    String cpfCnpj
    
    String name
    
    String email
    
    String phone
    
    PersonType personType
    
    String postalCode
    
    String address
    
    String addressNumber
    
    String addressComplement
    
    String district
    
    String city
    
    String state
```

2024-05-14 12:35 UTC, pedrosdev commented on src/main/groovy/com/mini/asaas/domain/base/BaseDomain.groovy
> +    Boolean deleted = false
Faltou coloca as linhas em branco entre os atributos. O Loh disse que tem que ser nesse estilo, pra todas as classes:
```suggestion
    Date dateCreated
    
    Date lastUpdated
    
    Boolean deleted = false
```

2024-05-14 12:35 UTC, pedrosdev commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +    String state
Aqui também, a questão do espaçamento
```suggestion
    String cpfCnpj
    
    String name
    
    String email
    
    String phone
    
    PersonType personType
    
    String postalCode
    
    String address
    
    String addressNumber
    
    String addressComplement
    
    String district
    
    String city
    
    String state
```

2024-05-14 12:35 UTC, pedrosdev commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +        addressNumber blank: true
Tu esqueceu do blank: false no addressNumber
```suggestion
        addressNumber blank: false
```

2024-05-14 13:07 UTC, NayaneBatista approved these changes

2024-05-14 13:55 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +        addressComplement blank: true, nullable: true
O complemento deve ter uma string ou ser null.. por isso o blank: true se torna inviável

2024-05-14 19:27 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/domain/base/BasePerson.groovy
> +abstract class BasePerson extends BaseDomain{
```suggestion
abstract class BasePerson extends BaseDomain {
```

2024-05-14 19:27 UTC, welingtonloh approved these changes

2024-05-14 19:28 UTC, merged