Templates para eventos enviados notificados por email
TrioParadaDuraa/mini-asaas pull request #48
Opened 2024-06-07 13:14 UTC by NayaneBatista

### Impacto (Descrever o que foi feito)

- Criado os arquivos de template .gsp no package "email" da "views"
- Padroniza estilização da mensagem com `template.css`

### PR Predecessora (Caso exista dependência de uma PR ou branch existente)

### Link da tarefa no GitHub Projects
[Templates para email](https://github.com/orgs/TrioParadaDuraa/projects/1/views/1?pane=issue&itemId=66432884)

### Link dos mockups (Se houver)

### Prints do desenvolvimento
![image](https://github.com/TrioParadaDuraa/mini-asaas/assets/70235376/ca41e73d-7cfa-44fd-8a51-9c5522dda2b9)

![image](https://github.com/TrioParadaDuraa/mini-asaas/assets/70235376/4f0934db-c7d1-41b5-bddb-7707b9e2d28f)

![image](https://github.com/TrioParadaDuraa/mini-asaas/assets/70235376/48c7984c-c097-40de-ad09-9b0f052d8e34)

![image](https://github.com/TrioParadaDuraa/mini-asaas/assets/70235376/ff23a3d1-4afc-4592-a949-35286325859d)

2024-06-07 13:36 UTC, pedrosdev commented on grails-app/views/email/createdTemplate.gsp
> +            <a class="button-homepage" href="${createLink(controller: 'login', action: 'auth')}">Acessar minha conta</a>
Esses links poderiam levar direto pra a listagem de cobranças, e daí se o usuário não tiver logado, o Spring Security vai pedir login e depois redirecionar pra página de cobranças

2024-06-07 13:50 UTC, pedrosdev commented
A gente também vai precisar de templates pra o email que vai ser enviado pra o Payer

2024-06-07 16:03 UTC, pedrosdev commented on grails-app/views/email/payer/createdTemplate.gsp
> +            <a class="button-homepage" href="${createLink(controller: 'payment', action: 'list')}">Acessar cobranças</a>
Pode ser

2024-06-07 16:16 UTC, pedrosdev approved these changes

2024-06-10 16:19 UTC, NayaneBatista commented
O client do email não renderizava o primeiro estilo corretamente, os templates foram alterados para a seguinte configuração
![image](https://github.com/TrioParadaDuraa/mini-asaas/assets/70235376/70c71a04-756e-4082-bad8-696f5d812bec)

2024-06-10 16:21 UTC, pedrosdev requested changes

2024-06-10 16:21 UTC, pedrosdev commented on grails-app/views/email/customer/createdTemplate.gsp
> +                                            <a href="${createLink(controller: 'payment', action: 'list')} target="_blank" style="color: #ffffff; text-decoration: none; font-weight: bold;">Acessar min
```suggestion
                                            <a href="${createLink(controller: 'payment', action: 'list')}" target="_blank" style="color: #ffffff; text-decoration: none; font-weight: bold;">Acessar minhas cobranças</a>
```

2024-06-10 16:24 UTC, pedrosdev commented
Eu gostava da logo do Asaas no topo :cry:. Não tem como colocar?

2024-06-11 13:18 UTC, kmurilo commented on grails-app/views/email/customer/createdTemplate.gsp
> +                                            <a href="${createLink(controller: 'payment', action: 'list')}" target="_blank" style="color: #ffffff; text-decoration: none; font-weight: bold;">Acessar mi
O createLink funcionou corretamente dentro do template?

2024-06-11 13:24 UTC, NayaneBatista commented on grails-app/views/email/customer/createdTemplate.gsp
> +                                            <a href="${createLink(controller: 'payment', action: 'list')}" target="_blank" style="color: #ffffff; text-decoration: none; font-weight: bold;">Acessar mi
Funcionou 😊

2024-06-11 13:38 UTC, pedrosdev commented on grails-app/views/email/customer/createdTemplate.gsp
> +                                            <a href="${createLink(controller: 'payment', action: 'list')}" target="_blank" style="color: #ffffff; text-decoration: none; font-weight: bold;">Acessar mi
Testei agora e não funciona pelo client de email. Teria um jeito de fazer funcionar rodando localmente ou o jeito é tirar mesmo?

2024-06-12 17:07 UTC, kmurilo commented on grails-app/views/email/customer/createdTemplate.gsp
> +                                            <a href="${createLink(controller: 'payment', action: 'list')}" target="_blank" style="color: #ffffff; text-decoration: none; font-weight: bold;">Acessar mi
O jeito é passar o link o já construído para dentro do template. 
Exemplo: grailsLinkGenerator.link

2024-06-12 20:56 UTC, kmurilo approved these changes

2024-06-12 20:56 UTC, merged