Página de criação de pagadores
TrioParadaDuraa/mini-asaas pull request #51
Opened 2024-06-07 17:31 UTC by NayaneBatista

### Impacto (Descrever o que foi feito)

- Criação em Atlas da página de cadastro de pagadores
- Acréscimo dos itens referentes a pagadores no menu da sidebar

### PR Predecessora (Caso exista dependência de uma PR ou branch existente)

### Link da tarefa no GitHub Projects
https://github.com/orgs/TrioParadaDuraa/projects/1/views/1?pane=issue&itemId=62414184

### Link dos mockups (Se houver)

### Prints do desenvolvimento
![image](https://github.com/TrioParadaDuraa/mini-asaas/assets/70235376/86120781-842e-4494-be1f-b1820bede82f)

2024-06-07 18:12 UTC, pedrosdev commented on grails-app/views/payer/index.gsp
> +<%@ page import="com.mini.asaas.utils.base.PersonType; com.mini.asaas.utils.enums.BrazilianState; com.mini.asaas.payer.Payer" %>
Pra quê servem esses imports de BrazilianState e Payer?

2024-06-07 18:14 UTC, Danichs requested changes

2024-06-07 18:14 UTC, Danichs commented on grails-app/views/utils/_sidebar.gsp
> +                    href="${createLink(controller: 'payer', action: 'list')}"
Deixa a sidebar ativa e dentro do menu : 

```suggestion
                    href="${createLink(controller: 'payer', action: 'list')}"
                    ${ controllerName == 'payer' && actionName == 'list' ? 'active' : '' }
```

2024-06-07 18:14 UTC, Danichs commented on grails-app/views/utils/_sidebar.gsp
> +                href="">
Deixa a sidebar ativa : 
```suggestion
                href="">
                ${ controllerName == 'payer' ? 'active' : '' }
```

2024-06-07 18:14 UTC, Danichs commented on grails-app/views/utils/_sidebar.gsp
> +                    href="${createLink(controller: 'payer', action: 'index')}"
```suggestion
                    href="${createLink(controller: 'payer', action: 'index')}"
                    ${ controllerName == 'payer' && actionName == 'index' ? 'active' : '' }
```

2024-06-07 18:26 UTC, Danichs approved these changes

2024-06-07 18:35 UTC, NayaneBatista commented on grails-app/views/payer/index.gsp
> +<%@ page import="com.mini.asaas.utils.base.PersonType; com.mini.asaas.utils.enums.BrazilianState; com.mini.asaas.payer.Payer" %>
O enum tá errado mesmo pq não foi usado
revi também o domain do payer e não há nada que precisamos acessar de lá mesmo, vou corrigir!

2024-06-10 18:03 UTC, pedrosdev approved these changes

2024-06-12 12:19 UTC, kmurilo approved these changes

2024-06-12 12:19 UTC, merged